version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn clean test
      - run:
          name: Générer le rapport coco
          command: mvn jacoco:report
      - run:
          name: Télécharger le rapport sur coco
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}
  checkstyle:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

workflows:
  version: 2
  test:
    jobs:
      - test
      - checkstyle
